name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set version
      id: version
      run: echo ::set-output name=release_version::${GITHUB_REF#refs/*/}

    - name: Build Docker image
      run: |
        echo Building version ${{ steps.version.outputs.release_version }}...
        docker build . --file Dockerfile --tag alehoho/oo-ce-docker-license:${{ steps.version.outputs.release_version }}

    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push alehoho/oo-ce-docker-license:${{ steps.version.outputs.release_version }}
